export { SkeletonBase } from './SkeletonBase'
export { CarouselHeroSkeleton } from './CarouselHeroSkeleton'
export { AnimeBannerSkeleton } from './AnimeBannerSkeleton'
export { CardGridSkeleton } from './CardGridSkeleton'
export { AnimeCardGridSkeleton } from './AnimeCardGridSkeleton'
export { AnimeMainSkeleton } from './AnimeMainSkeleton'
export { HomeAsideSkeleton } from './HomeAsideSkeleton'
export { EpisodeContentSkeleton } from './EpisodeContentSkeleton'
export { FavoriteButtonSkeleton } from './FavoriteButtonSkeleton'
export { RelatedAnimesSkeleton } from './RelatedAnimesSkeleton'

